"""PDF export service for emission reports and questionnaire responses."""

from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def _build_header(title: str, company: str, date_str: str) -> list:
    """Build common PDF header elements."""
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "CustomTitle", parent=styles["Title"], fontSize=18, spaceAfter=6
    )
    subtitle_style = ParagraphStyle(
        "CustomSubtitle", parent=styles["Normal"], fontSize=10, textColor=colors.grey
    )
    return [
        Paragraph(title, title_style),
        Paragraph(f"{company} — Generated {date_str}", subtitle_style),
        Spacer(1, 0.3 * inch),
    ]


def generate_report_pdf(
    company_name: str,
    industry: str,
    region: str,
    year: int,
    scope1: float,
    scope2: float,
    scope3: float,
    total: float,
    methodology: str | None = None,
    confidence: float | None = None,
) -> bytes:
    """Generate a PDF for an emission report."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    elements = _build_header(f"Emission Report — {year}", company_name, date_str)

    # Company info table
    info_data = [
        ["Company", company_name],
        ["Industry", industry],
        ["Region", region],
        ["Reporting Year", str(year)],
    ]
    if methodology:
        info_data.append(["Methodology", methodology])
    if confidence is not None:
        info_data.append(["Confidence", f"{confidence:.0%}"])

    info_table = Table(info_data, colWidths=[2 * inch, 4 * inch])
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.Color(0.93, 0.93, 0.93)),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(info_table)
    elements.append(Spacer(1, 0.3 * inch))

    # Emissions table
    elements.append(Paragraph("Greenhouse Gas Emissions (tCO2e)", styles["Heading2"]))
    emission_data = [
        ["Scope", "Emissions (tCO2e)", "% of Total"],
        ["Scope 1 — Direct", f"{scope1:,.2f}", f"{scope1/total*100:.1f}%" if total else "—"],
        ["Scope 2 — Indirect (Energy)", f"{scope2:,.2f}", f"{scope2/total*100:.1f}%" if total else "—"],
        ["Scope 3 — Value Chain", f"{scope3:,.2f}", f"{scope3/total*100:.1f}%" if total else "—"],
        ["Total", f"{total:,.2f}", "100.0%"],
    ]
    emission_table = Table(emission_data, colWidths=[2.5 * inch, 2 * inch, 1.5 * inch])
    emission_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.Color(0.15, 0.35, 0.2)),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BACKGROUND", (0, -1), (-1, -1), colors.Color(0.93, 0.93, 0.93)),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(emission_table)
    elements.append(Spacer(1, 0.3 * inch))

    # Footer
    elements.append(Paragraph(
        "This report was generated by CarbonScope using the GHG Protocol methodology. "
        "Emission factors from the EPA and IEA databases.",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey),
    ))

    doc.build(elements)
    return buf.getvalue()


def generate_questionnaire_pdf(
    company_name: str,
    questionnaire_title: str,
    questions: list[dict[str, Any]],
) -> bytes:
    """Generate a PDF for questionnaire responses."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    elements = _build_header(f"Questionnaire: {questionnaire_title}", company_name, date_str)

    q_style = ParagraphStyle(
        "QuestionStyle", parent=styles["Normal"], fontSize=10,
        fontName="Helvetica-Bold", spaceAfter=4,
    )
    a_style = ParagraphStyle(
        "AnswerStyle", parent=styles["Normal"], fontSize=10,
        leftIndent=12, spaceAfter=8,
    )
    cat_style = ParagraphStyle(
        "CategoryStyle", parent=styles["Normal"], fontSize=8,
        textColor=colors.grey, leftIndent=12,
    )

    for q in questions:
        num = q.get("question_number", "")
        text = q.get("question_text", "")
        answer = q.get("human_answer") or q.get("ai_draft_answer") or "No response provided."
        category = q.get("category") or ""
        q_status = q.get("status", "draft")

        status_label = {"approved": "[APPROVED]", "reviewed": "[REVIEWED]", "draft": "[DRAFT]"}.get(q_status, "")

        elements.append(Paragraph(f"Q{num}. {text} {status_label}", q_style))
        if category:
            elements.append(Paragraph(f"Category: {category}", cat_style))
        elements.append(Paragraph(answer, a_style))
        elements.append(Spacer(1, 0.1 * inch))

    elements.append(Spacer(1, 0.3 * inch))
    elements.append(Paragraph(
        "Generated by CarbonScope — AI-assisted sustainability questionnaire platform.",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey),
    ))

    doc.build(elements)
    return buf.getvalue()
