"""SSE (Server-Sent Events) route for real-time push notifications."""

from __future__ import annotations

import asyncio
import json
import logging

from fastapi import APIRouter, Depends, Request
from fastapi.responses import StreamingResponse

from api.deps import get_current_user
from api.limiter import limiter
from api.models import User
from api.services.event_bus import Subscription

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/events", tags=["events"])

_HEARTBEAT_INTERVAL = 30  # seconds


async def _event_stream(request: Request, company_id: str):
    """Async generator that yields SSE-formatted events."""
    with Subscription(company_id) as queue:
        while True:
            try:
                if await request.is_disconnected():
                    break
                payload = await asyncio.wait_for(queue.get(), timeout=_HEARTBEAT_INTERVAL)
                event_type = payload.get("event", "message")
                data = json.dumps(payload.get("data", {}))
                yield f"event: {event_type}\ndata: {data}\n\n"
            except asyncio.TimeoutError:
                if await request.is_disconnected():
                    break
                # Send heartbeat to keep the connection alive
                yield ": heartbeat\n\n"
            except asyncio.CancelledError:
                break


@router.get("/subscribe")
@limiter.limit("10/minute")
async def subscribe(
    request: Request,
    user: User = Depends(get_current_user),
):
    """Subscribe to real-time events for the current user's company.

    Returns a text/event-stream response. Events include:
    - alert.created: new alerts generated by the scheduler
    - alert.acknowledged: an alert was marked as read
    """
    return StreamingResponse(
        _event_stream(request, user.company_id),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",  # disable nginx buffering
        },
    )
